version: "3.5"

services:
  postgres-local:
    image: quay.io/soharaki/addresscode-database:latest
    container_name: postgres-local
    ports:
      - 5432:5432
    volumes:
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRESQL_DATABASE: address
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres-local

  pgadmin4:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres-local

  addresscode-service:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
      - 1898:1898
    environment:
      POSTGRESQL_SERVICE_HOST: postgres-local
    links:
      - postgres-local
    depends_on:
      - postgres-local

volumes:
  pgadmin4:
    driver: local
  pglog:
    driver: local
