version: "3"
services:
  jdk-maven:
    build: .
    command: sleep infinity
    environment:
      - VARIANT=15
      - INSTALL_MAVEN=true
      - MAVEN_VERSION=3.6.3
      - USERNAME=vscode
    ports:
      - "8080:8080"
      - "1898:1898"
    volumes:
      - $HOME/.ssh:/home/vscode/.ssh
      - $HOME/.gitconfig:/home/vscode/.gitconfig
      - ..:/workspace
      - .m2:/home/vscode/.m2

  postgres:
    image: quay.io/soharaki/addresscode-database:v0.0.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRESQL_DATABASE: address
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:5.3
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres
    restart: always

volumes:
  pgadmin4:
    driver: local
  pglog:
    driver: local
